### ISSUE TITLE
error: Cursor skipped --> have not standard windows name 

### ISSUE THREAD

**Issue by MarcoPasta** [SystemRage/Metamorphosis#3]
Hi, 

i try to convert the 3dgarro windows-xp cursor theme for my arch system but when i tried to convert the icons i got this error message on every icon, the file name is mostly 3dgarro.cu, 3dgmove.cur etc.. 

Any help?

**Comment by TanvirTaaha** [comment]
faced same problem

**Comment by SystemRage** [comment]
Sorry for the late reply, i abandoned a bit this project but
in the coming times i'll give it a refresh.

To answer your question the [cursor set](http://www.rw-designer.com/cursor-set/windows-xp) you have chosen is twofold unlucky:
1) you have to manually remap all names with standard Windows cursor names (fixing problem for this set and similar):
`Arrow, Help, AppStarting, Wait, Crosshair ` etc, etc...
for example:    
3dgarro.cur ---> Arrow.cur  
banana.ani ---> Wait.ani
etc, etc...

BUT

2) conversion process delegated to Iconolatry.py that reads `.cur`s and `.ani`s (group of `.cur`s)
can *by now* only handle RGBA (32 bit) and RGB (24 bit) images and your cursor set is created with bit depth = 4.

**Comment by SystemRage** [comment]
with the latest you can convert anything you want (after the renaming thing)
